<?php

/**
 * @file
 * This is a short desc.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\yashaswi_exercise\Event\UserLoginEvent;


/**
 * Implements hook_form_alter().
 */
function yashaswi_exercise_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  // Gets called whenever form is opened.
  // Calling service to call getName func from CustomService.php.
  $data = \Drupal::service('custom_service')->getName();
  // Prints the value provided in the config form.
  print_r($data);
}

/**
 * Implements hook_theme().
 */
function yashaswi_exercise_theme($existing, $type, $theme, $path) {

  return [
  // Name for the template file (html.twig)
    'controller_template' => [
  // Defined variables to be returned.
      'variables' => [
  // Can provide default value for markup here.
        'markup' => "",
  // Can prove default value for hexcode here.
        'hexcode' => "",
      ],
    ],
  ];

}

/**
 * @file
 * Contains custom_events.module.
 */


/**
 * Implements hook_user_login().
 */
function yashaswi_exercise_user_login($account) {
  // Instantiate our event.
  $event = new UserLoginEvent($account);

  // Get the event_dispatcher service and dispatch the event.
  $event_dispatcher = \Drupal::service('event_dispatcher');
  $event_dispatcher->dispatch($event, UserLoginEvent::EVENT_NAME);
}

function yashaswi_exercise_page_attachments_alter(array &$attachments) {
  $route_match = \Drupal::routeMatch();
  $route_name = $route_match->getRouteName();


  if ($route_name === 'comment.admin') {
    $attachments['#attached']['library'][] = 'yashaswi_exercise/css_lib';

  }
  elseif($route_name=='entity.node.canonical'){
    $attachments['#attached']['library'][] = 'yashaswi_exercise/css_lib';

  }
}
