config_block.config_form:
  path: '/config-form-exercise' #giving path to Configform.php
  defaults:
    _form: '\Drupal\config_block\Form\ConfigForm' #defining the path
    _title: 'config user details' #title given for config form
  requirements:
    _permission: 'config form permission' #created new pemission with admin route enabled
  options:
    _admin_route: TRUE
